// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Expense struct {
	ID              uuid.UUID
	ExpenseID       uuid.UUID
	TotalExpense    int32
	TransactionDate time.Time
	Description     sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UserID          uuid.UUID
}

type ExpenseType struct {
	ID          uuid.UUID
	Description string
}

type Income struct {
	ID              uuid.UUID
	IncomeID        uuid.UUID
	TotalIncome     int32
	TransactionDate time.Time
	Description     sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UserID          uuid.UUID
}

type IncomeType struct {
	ID          uuid.UUID
	Description string
}

type User struct {
	ID        uuid.UUID
	Username  string
	HashPass  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Section   string
	Role      string
}
