// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
  id,
  username,
  hash_pass,
  created_at,
  updated_at,
  role,
  section,
  email
  ) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, username, hash_pass, created_at, updated_at, email, section, role
`

type CreateUsersParams struct {
	ID        uuid.UUID
	Username  string
	HashPass  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
	Section   string
	Email     string
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUsers,
		arg.ID,
		arg.Username,
		arg.HashPass,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Role,
		arg.Section,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashPass,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Section,
		&i.Role,
	)
	return i, err
}
